/*
 * Copyright (C) 2018 Usuario
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.erickweil.labmanager.server.swing;

import br.erickweil.labamanger.common.BroadcasterMessage.Messages;
import br.erickweil.labamanger.common.Program;
import br.erickweil.labamanger.common.Program.StartType;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class JanelaNovoPrograma extends javax.swing.JFrame {

    private final JanelaConfiguracoes janelaConfiguracoes;
    public static final int REGEX_EXATAMENTE = 0;
    public static final int REGEX_INICIACOM = 1;
    public static final int REGEX_TERMINACOM = 2;
    public static final int REGEX_CONTEM = 3;
    public static final int REGEX_REGEX = 4;
    /**
     * Creates new form JanelaNovoPrograma
     */
    public JanelaNovoPrograma(JanelaConfiguracoes janelaConfiguracoes) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.janelaConfiguracoes = janelaConfiguracoes;
    }
    
    Program programEdit;
    public void inicializar(int roweditindex)
    {
        Program program = null;
        if(roweditindex >= 0)
        {
            DefaultTableModel model = (DefaultTableModel) janelaConfiguracoes.table_programas.getModel();
            String nome = (String)model.getValueAt(roweditindex, 0);
            List<Program> programs = janelaConfiguracoes.server.programs;
            
            for(Program p : programs)
            {
                if(p.name.equalsIgnoreCase(nome))
                {
                    program = p;
                    break;
                }
            }
            if(program != null)
            {
                input_addprograma_nome.setText(program.name);
                input_addprograma_caminho.setText(program.path);
                input_addprograma_janela.setText(program.window);
                input_addprograma_processo.setText(program.process);
                combo_addprograma_regexjanela.setSelectedIndex(0);
                combo_addprograma_regexprocesso.setSelectedIndex(0);
                combo_addprograma_inicializacao.setSelectedItem(program.start.toString());
                combo_addprograma_modo.setSelectedItem(program.mode.toString());
                
                button_addprograma.setText("Editar");
            }
        }
        
        if(program == null)
        {
            input_addprograma_nome.setText("");
            input_addprograma_caminho.setText("");
            input_addprograma_janela.setText("");
            input_addprograma_processo.setText("");
            combo_addprograma_regexjanela.setSelectedIndex(0);
            combo_addprograma_regexprocesso.setSelectedIndex(0);
            combo_addprograma_inicializacao.setSelectedIndex(0);
            combo_addprograma_modo.setSelectedIndex(0);
            
            button_addprograma.setText("Adicionar");
        }
        
        programEdit = program;
    }

    private String combo_text(JComboBox c)
    {
        int index = c.getSelectedIndex();
        if(index != -1)
        {
            String selected = (String)c.getItemAt(index);
            if(selected != null && !selected.isEmpty())
            {
                return selected;
            }
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        combo_addprograma_inicializacao = new javax.swing.JComboBox();
        button_addprograma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        combo_addprograma_modo = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        input_addprograma_processo = new javax.swing.JTextField();
        input_addprograma_caminho = new javax.swing.JTextField();
        input_addprograma_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input_addprograma_janela = new javax.swing.JTextField();
        combo_addprograma_regexprocesso = new javax.swing.JComboBox<>();
        combo_addprograma_regexjanela = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Inicialização:");

        combo_addprograma_inicializacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "logon", "blacklist", "manual" }));

        button_addprograma.setText("Adicionar");
        button_addprograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addprogramaActionPerformed(evt);
            }
        });

        jLabel1.setText("Modo de Bloqueio:");

        combo_addprograma_modo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "processo", "janela" }));
        combo_addprograma_modo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_addprograma_modoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do Programa"));
        jPanel1.setToolTipText("");

        input_addprograma_processo.setText("Notepad.exe");

        input_addprograma_caminho.setText("C:/Windows/notepad\\.exe");

        input_addprograma_nome.setText("Notepad");
        input_addprograma_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_addprograma_nomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome:");

        jLabel6.setText("Caminho:");

        jLabel7.setText("Processo:");

        jLabel2.setText("Janela:");

        input_addprograma_janela.setText("^.* \\- Bloco de Notas$");
        input_addprograma_janela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_addprograma_janelaActionPerformed(evt);
            }
        });

        combo_addprograma_regexprocesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "exatamente", "inicia com", "termina com", "contém", "regex", " " }));

        combo_addprograma_regexjanela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "exatamente", "inicia com", "termina com", "contém", "regex" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_addprograma_caminho, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(input_addprograma_nome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_addprograma_regexprocesso, 0, 120, Short.MAX_VALUE)
                            .addComponent(combo_addprograma_regexjanela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_addprograma_processo)
                            .addComponent(input_addprograma_janela))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(input_addprograma_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_addprograma_caminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input_addprograma_processo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_addprograma_regexprocesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_addprograma_janela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_addprograma_regexjanela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_addprograma_inicializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_addprograma_modo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_addprograma, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(combo_addprograma_inicializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_addprograma_modo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_addprograma)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_addprograma_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_addprograma_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_addprograma_nomeActionPerformed

    private void button_addprogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addprogramaActionPerformed
        //
        String name = input_addprograma_nome.getText();
        String path = input_addprograma_caminho.getText();
        String processo = input_addprograma_processo.getText();
        String janela = input_addprograma_janela.getText();
        StartType inicializacao = Program.StartType.manual;
        Program.BlockMode modo = Program.BlockMode.processo;


        String selected = combo_text(this.combo_addprograma_inicializacao);
        if(selected != null && !selected.isEmpty())
        {
            inicializacao = StartType.valueOf(selected);
        }

        selected = combo_text(this.combo_addprograma_modo);
        if(selected != null && !selected.isEmpty())
        {
            modo = Program.BlockMode.valueOf(selected);
        }
        
        int index = this.combo_addprograma_regexprocesso.getSelectedIndex();
        switch(index)
        {
            case REGEX_REGEX:        
            case REGEX_EXATAMENTE:   break;
            case REGEX_INICIACOM:   processo = "^"+processo+".*$"; break;
            case REGEX_TERMINACOM:  processo = "^.*"+processo+"$"; break;
            case REGEX_CONTEM:      processo = "^.*"+processo+".*$"; break;
        }
        
        index = this.combo_addprograma_regexjanela.getSelectedIndex();
        switch(index)
        {
            case REGEX_REGEX:        
            case REGEX_EXATAMENTE:   break;
            case REGEX_INICIACOM:   janela = "^"+janela+".*$"; break;
            case REGEX_TERMINACOM:  janela = "^.*"+janela+"$"; break;
            case REGEX_CONTEM:      janela = "^.*"+janela+".*$"; break;
        }

        
        if(programEdit == null)
        {
            Program p = new Program(name, path, processo, janela, inicializacao , false, modo);
            janelaConfiguracoes.server.programs.add(p);
        }
        else
        {
            programEdit.name = name;
            programEdit.path = path;
            programEdit.process = processo;
            programEdit.window = janela;
            programEdit.start = inicializacao;
            programEdit.mode = modo;
        }
        
        janelaConfiguracoes.updateValues();
        janelaConfiguracoes.server.sendMessage("all", Messages.blacklist);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_button_addprogramaActionPerformed

    private void combo_addprograma_modoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_addprograma_modoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_addprograma_modoActionPerformed

    private void input_addprograma_janelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_addprograma_janelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_addprograma_janelaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_addprograma;
    private javax.swing.JComboBox combo_addprograma_inicializacao;
    private javax.swing.JComboBox combo_addprograma_modo;
    private javax.swing.JComboBox<String> combo_addprograma_regexjanela;
    private javax.swing.JComboBox<String> combo_addprograma_regexprocesso;
    private javax.swing.JTextField input_addprograma_caminho;
    private javax.swing.JTextField input_addprograma_janela;
    private javax.swing.JTextField input_addprograma_nome;
    private javax.swing.JTextField input_addprograma_processo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
