/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.erickweil.test;

import br.erickweil.streaming.StreamWatcher.ImageListener;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class StreamingWindow extends javax.swing.JFrame implements ImageListener{
    /**
     * Creates new form StreamingWindow
     */
    public StreamingWindow() {
        initComponents();
    }
    

    @Override
    public void setImage(BufferedImage img) {
        /*int screen_width = img.getWidth();
        int screen_height = img.getHeight();
        float aspect_ratio = (float)screen_width / (float)screen_height;
        int new_width = 1024;
        int new_height = (int)((float)new_width/aspect_ratio);
        //Image low_screen = img.getScaledInstance(new_width, new_height, BufferedImage.SCALE_DEFAULT);
        BufferedImage low_screen = new BufferedImage(new_width,new_height, BufferedImage.TYPE_INT_RGB);
        Graphics g = low_screen.createGraphics();
        g.drawImage( img, 0, 0, new_width, new_height, 0, 0 , screen_width, screen_height, null);
        g.dispose();*/
        //SurfaceBlur surf = new SurfaceBlur(img, 4, 1, 50, 1);
        //BufferedImage new_img = surf.run();
        //ImageIcon icon = new ImageIcon(low_screen);
        
        ImageIcon icon = new ImageIcon(img);
        label_fundo.setIcon(icon);
        //            int screen_width = img.getWidth();
        //    int screen_height = img.getHeight();
        
        //    System.out.println("SETING IMG: "+screen_width+","+screen_height);
        //label_fundo.setText("Funcionou");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_fundo.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StreamingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StreamingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StreamingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StreamingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StreamingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_fundo;
    // End of variables declaration//GEN-END:variables
}
